[project]
name = "is-she-real"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.111",
  "uvicorn>=0.30",
  "httpx>=0.27",
  "pydantic>=2.7",
  # add anything else you import
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
